"""Changed tables

Revision ID: fe1309257ff3
Revises: de28c39b35e4
Create Date: 2025-06-15 04:21:04.921560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1309257ff3'
down_revision: Union[str, None] = 'de28c39b35e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.add_column('processed_files', sa.Column('time_processed', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('processed_files', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('processed_files', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('processed_files', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('processed_files', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'processed_files', ['file_hash'])
    op.create_foreign_key(None, 'processed_files', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'processed_files', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processed_files', type_='foreignkey')
    op.drop_constraint(None, 'processed_files', type_='foreignkey')
    op.drop_constraint(None, 'processed_files', type_='unique')
    op.drop_column('processed_files', 'collection_id')
    op.drop_column('processed_files', 'owner_id')
    op.drop_column('processed_files', 'file_hash')
    op.drop_column('processed_files', 'filename')
    op.drop_column('processed_files', 'time_processed')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
