name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        cp .env.sample .env
        docker compose up -d
        docker compose ps

